name: Keep SIMULADORES Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # executa a cada 10 minutos
  workflow_dispatch:        # permite rodar manualmente tamb√©m

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Simulador App
        run: | 
          curl -I https://simulador-ggdp.onrender.com/ || true
          curl -I https://promove-ggdp.streamlit.app/ || true
